### PR TITLE
Vega year update

### PR DESCRIPTION
**Pull request by favelava**
Added vega logic to relevant plots which colors the background of the plots by year.

### CODE REVIEW

**Comment by atc3** [comment]
Can you add a picture of the change?

**Comment by favelava** [comment]
Group Stack Plot:
Screen Shot 2022-01-19 at 1 01 38 PM

Location Date Plot:
Screen Shot 2022-01-19 at 1 02 14 PM

**Comment by atc3** [comment]
great, thanks!

**Review by atc3 — APPROVED** [review]
LGTM

**Pull request merged**
